const keyCodes = {
  // Numbers
  Digit0: "0",
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",

  // Letters
  A: "A",
  B: "B",
  C: "C",
  D: "D",
  E: "E",
  F: "F",
  G: "G",
  H: "H",
  I: "I",
  J: "J",
  K: "K",
  L: "L",
  M: "M",
  N: "N",
  O: "O",
  P: "P",
  Q: "Q",
  R: "R",
  S: "S",
  T: "T",
  U: "U",
  V: "V",
  W: "W",
  X: "X",
  Y: "Y",
  Z: "Z",

  // Function keys
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F5: "F5",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  F10: "F10",
  F11: "F11",
  F12: "F12",
  F13: "F13",
  F14: "F14",
  F15: "F15",
  F16: "F16",
  F17: "F17",
  F18: "F18",
  F19: "F19",
  F20: "F20",
  F21: "F21",
  F22: "F22",
  F23: "F23",
  F24: "F24",

  // Punctuation/Symbols
  Backtick: "`",
  Tilde: "~",
  Exclamation: "!",
  At: "@",
  Hash: "#",
  Dollar: "$",
  Percent: "%",
  Caret: "^",
  Ampersand: "&",
  Asterisk: "*",
  ParenthesisLeft: "(",
  ParenthesisRight: ")",
  Minus: "-",
  Underscore: "_",
  Equals: "=",
  Plus: "+",
  BracketLeft: "[",
  BracketRight: "]",
  BraceLeft: "{",
  BraceRight: "}",
  Backslash: "\\",
  Pipe: "|",
  Semicolon: ";",
  Colon: ":",
  Quote: '"',
  Apostrophe: "'",
  Comma: ",",
  LessThan: "<",
  Period: ".",
  GreaterThan: ">",
  Slash: "/",
  Question: "?",

  // Whitespace / Special
  Space: "Space",
  Tab: "Tab",

  // Locks
  CapsLock: "Capslock",
  NumLock: "Numlock",
  ScrollLock: "Scrolllock",

  // Editing
  Backspace: "Backspace",
  Delete: "Delete",
  Insert: "Insert",
  Enter: "Return", // aka Enter

  // Navigation
  ArrowUp: "Up",
  ArrowDown: "Down",
  ArrowLeft: "Left",
  ArrowRight: "Right",
  Home: "Home",
  End: "End",
  PageUp: "PageUp",
  PageDown: "PageDown",
  Escape: "Escape", // aka Esc

  // Media keys
  VolumeUp: "VolumeUp",
  VolumeDown: "VolumeDown",
  VolumeMute: "VolumeMute",
  MediaPlayPause: "MediaPlayPause",
  MediaStop: "MediaStop",
  MediaNextTrack: "MediaNextTrack",
  MediaPreviousTrack: "MediaPreviousTrack",

  // Other
  PrintScreen: "PrintScreen",

  // Numpad
  Numpad0: "num0",
  Numpad1: "num1",
  Numpad2: "num2",
  Numpad3: "num3",
  Numpad4: "num4",
  Numpad5: "num5",
  Numpad6: "num6",
  Numpad7: "num7",
  Numpad8: "num8",
  Numpad9: "num9",
  NumpadDecimal: "numdec",
  NumpadAdd: "numadd",
  NumpadSubtract: "numsub",
  NumpadMultiply: "nummult",
  NumpadDivide: "numdiv"
};

export default keyCodes;
